{% set name = "cf_pandas" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cf_pandas-{{ version }}.tar.gz
  sha256: 5a9a98dfb59cf0edbf1515a3ed46cc785abbdcada179277aa067a0db664fdf6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - pandas
    - python >=3.6
    - regex

test:
  imports:
    - cf_pandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/cf-pandas
  summary: an accessor for pandas objects that interprets CF attributes
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
    - lukecampbell
