{% set name = "cf_pandas" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cf_pandas-{{ version }}.tar.gz
  sha256: f0548874aec327e4ee0dcdc11429778f06e7450fc1f3d6e8aa74a0de77c88097

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - pandas
    - python >=3.6
    - regex

test:
  imports:
    - cf_pandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/cf-pandas
  summary: an accessor for pandas objects that interprets CF attributes
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
    - lukecampbell
